// <auto-generated />
namespace LivrariaCactus_Balao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigracaoDeFuncionamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracaoDeFuncionamento));
        
        string IMigrationMetadata.Id
        {
            get { return "202003250415484_MigracaoDeFuncionamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
